import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import AppHeader from "@/components/app_header";
import AppFooter from "@/components/app_footer";
import { getSessionId } from "@/utils/session_store";
const inter = Inter({ subsets: ["latin"] });

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>,) {


  return (
    <>
      <AppHeader
      
      />
      {children}
      <AppFooter />
    </>
  );
}
